server:
  port: ${PORT:8081}
  error:
    include-message: always
    include-stacktrace: never

eureka:
  instance:
    instance-id: ${spring.application.name}:${eureka.instance.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: product-service
  webflux:
    base-path: /integrator/products

