

server:
  port: ${PORT:9991}
  error:
    include-message: always
    include-stacktrace: never
eureka:
  instance:
    instance-id: ${spring.application.name}:${eureka.instance.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: oauth-service




